pipeline {
    agent any
    
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '''
                    ssh -t -t user@host 'bash -s << 'ENDSSH'
                    sudo export DISPLAY=:0 
                    sudo Xvfb :0 -ac -screen 0 1024x768x24 &
                    sh 'mvn test -Dwebdriver.chrome.driver=/var/lib/jenkins/workspace/ySampleWebApp_bitwiseman-patch-1/src/test/resources/webdriver/binaries/linux/googlechrome/64bit/chromedriver'
            ENDSSH'
                 '''
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
